# Generated by Django 5.0.4 on 2024-05-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenciler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adSoyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('hakkinda', models.TextField(max_length=100, verbose_name='Hakkında')),
                ('resim', models.FileField(blank=True, null=True, upload_to='ogrenci_resmi', verbose_name='Resim')),
            ],
        ),
    ]
